"""notsure what is wrong

Revision ID: 109cea68dd1a
Revises: 3f689893585e
Create Date: 2015-06-19 14:53:50.960939

"""

# revision identifiers, used by Alembic.
revision = '109cea68dd1a'
down_revision = '3f689893585e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
