"""initial migration

Revision ID: 3a693f41d5dc
Revises: None
Create Date: 2015-06-03 20:21:27.847085

"""

# revision identifiers, used by Alembic.
revision = '3a693f41d5dc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
