"""added email to user model

Revision ID: 430c7ebb62eb
Revises: 9100cd035f4
Create Date: 2015-06-05 12:30:01.578584

"""

# revision identifiers, used by Alembic.
revision = '430c7ebb62eb'
down_revision = '9100cd035f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    ### end Alembic commands ###
