"""empty message

Revision ID: 4b6a7934159
Revises: 547436c1affd
Create Date: 2015-06-16 19:42:23.577180

"""

# revision identifiers, used by Alembic.
revision = '4b6a7934159'
down_revision = '547436c1affd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
