"""added confirmed field

Revision ID: 5bbfabe82f5
Revises: 430c7ebb62eb
Create Date: 2015-06-05 17:18:10.617686

"""

# revision identifiers, used by Alembic.
revision = '5bbfabe82f5'
down_revision = '430c7ebb62eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
